import { number, object, string } from "yup";

export const validationSchema = object({
    name: string().required("O nome é obrigatório!"),
    contract: string().required("Tipo de Contrato é obrigatório!"),
    situation: string().required("O tipo da situação é obrigatória"),
    start: string().required("O Campo é obrigatório"),
    admission: string().required("O Campo é obrigatório"),
    occupation: string().required("O Campo é obrigatório"),
    computer: string(),
    payment: string().required("O Campo é obrigatório"),
    cost_center: string().required("O Campo é obrigatório"),
    MEI: string(),
    hours: string().required("O Campo é obrigatório"),
    city: string().required("O Campo é obrigatório"),
    coordinator: string().required("O Campo é obrigatório"),
    contact: string().required("O Campo é obrigatório"),
    birth: string().required("O Campo é obrigatório"),
    CPF: string().required("O Campo é obrigatório"),
    identity: string().required("O Campo é obrigatório"),
    schooling: string().required("O Campo é obrigatório"),
    mother: string().required("O Campo é obrigatório"),
    sons: string().required("O Campo é obrigatório"),
    emergency_contact: string().required("O Campo é obrigatório"),
    responsible_emergency: string().required("O Campo é obrigatório"),
    address: string().required("O Campo é obrigatório"),
    email: string().required("O Campo é obrigatório"),
    status: string().required("O Campo é obrigatório"),
    equipment_id: string(),
  });

export const initialValues ={
    id: "",
    name: "",
    contract: "",
    situation: "",
    start: "",
    admission: "",
    occupation: "",
    computer: "",
    payment: "",
    cost_center: "",
    MEI: "",
    hours: "",
    city: "",
    coordinator: "",
    contact: "",
    birth: "",
    CPF:"",
    identity: "",
    schooling: "",
    mother: "",
    sons: "",
    emergency_contact: "",
    responsible_emergency: "",
    address: "",
    email: "",
    status: "",
    equipment_id: "",
}